// Shared data — projects, bio, meta.

const PORTFOLIO_DATA = {
  visible: (p) => !p.wip && !p.minor,
  name: 'Yao Wang',
  kanji: '王瑶',
  tagline:
    'Design research on computational fabrication, soft and active materials, and how people and machines make things together.',
  affiliation: 'MDes Mediums · Harvard GSD',
  prev: 'RISD · Industrial Design',
  linkedin: 'https://www.linkedin.com/in/yao-wang-gsd/',
  email: 'yolanda_wang@gsd.harvard.edu',
  emailAlt: 'yolandaw@mit.edu',
  date: 'Spring 2026',
  session: '26-04',
  projects: [
    {
      id: 'tpu',
      locked: true,
      short: '3D printing on-fabric sensing mechanisms for smart textiles',
      venue: 'CHI 2027, under review',
      thumb: 'projects/assets/senfabric/sf00-thumb.png',
      title: 'SenFabric',
      year: '2026',
    },
    {
      id: 'fluidic',
      short: 'a pneumatic boundary driven by frontal alpha asymmetry',
      venue: 'ACADIA 2026',
      thumb: 'projects/assets/withheld-air/wa02-participants.png',
      title: 'Withheld-Air',
      subtitle: 'A pneumatic boundary driven by frontal alpha asymmetry.',
      year: '2026',
      blurb: 'Withheld-Air is a translucent pneumatic boundary between two people in conversation. Frontal alpha asymmetry, read from one of them, drives a field of Y-shaped chambers whose auxetic-like contraction seals the boundary as it fills, reconstructing the distance between them as pressure, delay, and a closing line of sight.',
      tags: ['physiological interfaces', 'pneumatic architecture', 'responsive environment'],
      figure: 'The 8 × 4 Y-cell field in its inflated state, with the voids between chambers closed.',
      body: 'The project investigates social withdrawal: disengaging from an encounter without leaving it, and asks how pre-verbal withholding might accumulate in a shared space. FAA is treated as a provisional index rather than a measure of emotion; what the project tests is what such a signal does once it is granted authority over shared space. Two departures from EEG-driven installation work set it up. The signal is read from one participant and imposed on a boundary both inhabit, so the architecture takes a side rather than mediating neutrally. And the pneumatic system does not animate form: as the chambers inflate, the apertures contract inward rather than expanding outward.',
      meta: [
        ['role', 'First author'],
        ['context', 'Harvard GSD · SCI 6511 Embodied Architectures · with Selina Yanan Zhou and Yuhan Ye'],
        ['output', 'ACADIA 2026 poster · 8 × 4 pneumatic field · four pilot dyads'],
        ['tools', 'Muse 2 EEG · Python · Wi-Fi smart plug · fan · PE film · Zund cutter with heated tip'],
        ['status', 'Poster submitted'],
      ],
      process: [
        'Treat FAA as a provisional index rather than a measure of emotion, and test how it behaves when it controls shared space.',
        'Design the boundary from a single Y-shaped cell tessellated into an 8 × 4 array. A hexagonal cell expands outward and a slit shuts like a shutter; the Y-cell opens in one direction and seals as it fills.',
        'Generate seam paths from the parametric model and weld layered PE film on a Zund cutter with a flat-tip soldering iron mounted on the gantry.',
        'Stream Muse 2 channels at 256 Hz, compute FAA over 8–13 Hz at about 16.6 Hz, and switch a Wi-Fi smart plug whenever the signal falls below the session baseline. No magnitude threshold and no minimum duration.',
        'Run four pilot dyads of 120 to 309 s. The trigger condition held between 32 and 49 percent of each session, and chamber pressure follows accumulated time below baseline rather than any single crossing.',
      ],
    },
    {
      id: 'climbit',
      proto: true,
      venue: 'MIT HARD MODE Hackathon, WINNER',
      short: 'a handheld dodecahedron that turns grip training into a climbing game',
      title: 'Climbit',
      subtitle: 'Grip training as an AI-driven climbing adventure, played through a handheld tangible controller.',
      year: '2026',
      blurb: 'Finger strength tools are static and repetitive. Climbit is a dodecahedron-shaped handheld object with printed holds and pressure sensors between them, so where and how hard the player grips drives a first-person climb.',
      tags: ['tangible interfaces', 'hardware prototyping', 'game controllers'],
      thumb: 'projects/assets/climbit/cb00-thumb.png',
      figures: [
        ['assets/climbit/cb01-device.jpg', 'The dodecahedron body with TPU holds on its faces. Pressure sensors sit between the holds.'],
        ['assets/climbit/cb02-game.jpg', 'Grip position and force drive a first-person climb in Unity, with AI-generated events and status returned to the player.'],
      ],
      body: 'The body is printed in PLA and the holds on its faces in TPU, so the grip is soft where the hand lands. Pressure sensors sit between the holds and read finger position and force; a microcontroller passes the readings to a Unity climb, and a vibration motor at the centre returns haptic feedback. Grip timing, pressure and rhythm are tracked, and the Claude API generates story events and short missions from those patterns, so a pause or a change of rhythm turns into something happening on the route.',
      meta: [
        ['role', 'Concept, industrial design, assembly, 3D printing'],
        ['context', 'MIT HARD MODE: Hardware x AI Hackathon'],
        ['output', 'Working prototype · Winner, Bambu Labs Prize'],
        ['tools', 'Arduino · pressure sensors · vibration motor · PLA and TPU printing · Unity · Claude API'],
        ['link', 'devpost.com/software/climbit-team-4'],
      ],
      process: [
        'Start from the gap between grip trainers and climbing: squeezing a static device gives no route, no feedback and no reason to continue.',
        'Settle on a dodecahedron so the hand meets a hold in any orientation, and iterate the form until it is comfortable to grip while still holding the sensors and electronics.',
        'Print the body in PLA and the holds in TPU, embed pressure sensors between the holds and a vibration motor at the centre.',
        'Read the sensors on a microcontroller and pipe the data into a Unity climbing environment in real time.',
        'Map grip patterns, timing and pauses to AI-generated story events, so the training and the game are the same action.',
      ],
    },
    {
      id: 'clay',
      venue: 'RISD',
      short: 'a wall built turn by turn, each clay brick reshaped by whoever holds it next',
      thumb: 'projects/assets/squishy/sq08-hero.jpg',
      title: 'Squishy Assembly',
      subtitle: 'A human and a robotic arm take turns shaping clay bricks and stacking them into one wall.',
      year: '2024',
      blurb: 'The human shapes a brick and places it horizontally. The arm reads that brick, shapes a matching one and stacks it vertically. Each placement touches the previous one.',
      tags: ['robotic fabrication', 'feedback systems', 'human-machine collaboration'],
      figure: 'Three test builds: planned shape, finished wall, and which bricks came from the user and which from the arm.',
      body: 'Clay is soft, so neither side works from a fixed brick. The human shapes a 30 × 30 × 10 mm blank by hand. The arm presses the blank at a measured offset from the clamp centre. A YOLOv5 model trained on 500 labelled images reads brick type and position, and a paper gripper lifts the brick without distorting it.',
      meta: [
        ['role', 'Project ownership, conceptualization, experimentation'],
        ['context', 'Shenzhen, China · May–August 2024 · with Yuan Gao · instructor Yiqing Wang'],
        ['tools', 'Robotic arm · YOLOv5 · Python · clay'],
        ['output', 'Three test walls · shape grammar · documentation'],
      ],
      process: [
        'Take Peruvian stone walls as the reference: stones shaped and stacked against the form of their neighbours.',
        'Set three rules: the human places horizontally, the arm places vertically, every placement is adjacent to the previous one.',
        'Document the bricks as a shape grammar on a 4 × 3 grid, with four corner types.',
        'Train brick recognition on 500 labelled images and build a paper gripper that holds soft clay without changing it.',
        'Run three builds against a planned shape and record which bricks came from the user and which from the arm.',
      ],
    },
    {
      id: 'chair',
      venue: 'RISD',
      short: 'discarded branches held by ceramic joints printed to the ends they grip',
      thumb: 'projects/assets/sticky/st00-thumb.png',
      title: 'Sticky Node',
      subtitle: 'Discarded branches held together by ceramic joints printed to their own geometry.',
      year: '2024',
      blurb: 'Each twig is scanned, and a Grasshopper definition tweens between two scanned ends to build a joint that fits only those two. The joints are printed in clay on non-planar toolpaths and fired.',
      tags: ['organic forms', 'parametric connections', 'ceramic 3d printing'],
      figure: 'Two stools broken into twigs and joints, and the reconfiguration between them.',
      body: 'The branches came from yard trimmings left on the street. No twig repeats, so no joint repeats. The printed clay shrinks in the kiln, so the geometry is scaled up until the fired joint fits: 100% and 120% came out too small, 168% holds. Twigs and joints can be taken apart and recombined into the next stool.',
      meta: [
        ['role', 'Individual work'],
        ['context', 'Shenzhen, China · May–August 2024 · instructor Yiqing Wang'],
        ['tools', 'Grasshopper · ceramic 3D printer · non-planar toolpathing'],
        ['output', 'Two stools · joint library · documentation'],
      ],
      process: [
        'Collect discarded yard trimmings and scan each twig with its forks.',
        'Tween between two scanned ends in Grasshopper to generate the joint surface and its non-planar toolpath.',
        'Print at 3.5 mm/s through a 0.4 mm nozzle and test three scalings against shrinkage after firing.',
        'Assemble two stools, 6 twigs and 6 joints and 5 twigs and 5 joints, without glue or fasteners.',
        'Take the stools apart and recombine the twigs into new configurations.',
      ],
    },
    {
      id: 'handshake',
      venue: 'RISD',
      short: 'a handshake read by sensing gloves and left behind as a ceramic brick',
      thumb: 'projects/assets/oscillations/os00-thumb.png',
      title: 'Oscillations of Connection',
      subtitle: 'One handshake, read by a pair of sensing gloves, prints one ceramic brick.',
      year: '2024',
      blurb: 'A modular glove records pressure, skin response and hand angle through a handshake. Duration sets the outline of the brick and the sensor data sets the layer heights along it.',
      tags: ['parametric design', 'robotic fabrication', 'tangible data'],
      figure: 'Six recorded handshakes with their sensor traces and the brick each one produces.',
      body: 'Grip, duration and hand angle are the parts of a handshake a glove can measure. Each handshake gives one outline built from merged spirals, and the pressure, GSR and tilt readings are mapped to layer height along it. The brick is printed in clay, so nozzle height and spacing decide whether the coil holds.',
      meta: [
        ['role', 'Individual work'],
        ['context', 'Shenzhen, China · May–August 2024 · instructor Yiqing Wang'],
        ['tools', 'Arduino · pressure, GSR and tilt sensors · Grasshopper · ceramic 3D printer'],
        ['output', 'Sensing glove pair · six bricks · documentation'],
      ],
      process: [
        'Sort handshakes by grip, angle and duration into twelve positions between calm and intense.',
        'Measure hand geometry in plan and section and build a modular glove of wrist, palm, thumb and ring parts in three sizes.',
        'Wire four pressure sensors, two GSR sensors and one tilt sensor per hand to an Arduino.',
        'Generate the flat outline from handshake duration and the layer heights from the sensor data in Grasshopper.',
        'Print in clay, correcting nozzle height and horizontal spacing across three tests.',
      ],
    },
    {
      id: 'latent-goal',
      short: 'a maze generator that learns your habits from which way you turn',
      venue: 'MIT 16.460 Algorithmic HRI',
      title: 'Diagnostic Mazes',
      subtitle: 'The system designs the next maze from what it currently believes about the person playing.',
      year: '2025',
      blurb: 'A formula reads each fork\'s signal straight from the maze layout, so 18 hand-labeled forks cover 789 forks in the largest library. That is about 44× less labeling.',
      tags: ['HRI', 'preference learning', 'adaptive design'],
      figure: 'The maze as the question: four forks, each one testing a different tendency.',
      body: 'Most systems that learn a person\'s preferences pick the next question from a fixed, prepared set. This one builds the question. It holds an estimate of four tendencies: exploring, saving effort, collecting items, and taking risks. From a library of generated mazes it picks the maze expected to teach it the most, shows it, and updates the estimate from the branches the player takes at forks. Choosing the next maze takes about 5 ms.',
      meta: [
        ['role', 'Third author. Research framing, deriving fork signals from maze layout, evaluation design and figures'],
        ['context', 'MIT 16.460 Algorithmic Human-Robot Interaction, course research paper'],
        ['collaborators', 'Qiyao Chen, Haoyang Li'],
        ['tools', 'Python · Bayesian inference · maze generation'],
        ['output', 'Course research paper · maze libraries of 46, 134 and 263 mazes'],
        ['status', 'Course paper, 2025'],
      ],
    },
    {
      id: 'eeg-crochet',
      minor: true,
      short: 'crochet driven by brainwaves',
      title: 'EEG Crochet',
      year: '2024',
      blurb: 'Crochet rhythm and stitch density driven by a wearable EEG signal.',
      tags: ['eeg interfaces', 'computational craft', 'textile making'],
      figure: 'Stitch density against attention and relaxation channels over a 20-minute session.',
      body: 'A wearable EEG sets the rhythm and density of crochet, so attention and relaxation over a session show up as stitch density in the finished textile.',
      meta: [
        ['role', 'Sole author'],
        ['context', 'Studio probe'],
        ['tools', 'EEG · Arduino · crochet'],
        ['output', 'Textile artifacts · session logs'],
      ],
    },
    {
      id: 'lce',
      minor: true,
      short: 'embroidered patterns that program how a textile deforms',
      title: 'LCE Parametric Embroidery',
      year: '2024',
      blurb: 'LCE threads embroidered along parametric patterns to program deformation.',
      tags: ['responsive textiles', 'lce', 'parametric patterning'],
      figure: 'Embroidered LCE samples; deformation map across parametric stitch families.',
      body: 'Liquid-crystal-elastomer threads are embroidered along parametrically generated patterns. On actuation, the stitch family determines how the sample deforms.',
      meta: [
        ['role', 'Sole author'],
        ['context', 'Materials studio'],
        ['tools', 'LCE · embroidery machine · Grasshopper'],
        ['output', 'Sample library'],
      ],
    },
    {
      id: 'rockite',
      minor: true,
      short: 'cast Rockite reinforced by printed PLA bones',
      title: 'PLA-Reinforced Rockite Casting',
      year: '2023',
      blurb: 'Cast Rockite reinforced by printed PLA bones that follow the tensile lines.',
      tags: ['casting', 'multimaterial fabrication', 'hybrid structures'],
      figure: 'Cross-section: PLA skeleton inside cast Rockite shell.',
      body: 'Rockite takes compression but is brittle in tension, so PLA "bones" are printed to follow the expected tensile lines and cast into the pour.',
      meta: [
        ['role', 'Sole author'],
        ['context', 'Materials studio'],
        ['tools', 'FDM printing · Rockite casting · mold-making'],
        ['output', 'Cast specimens'],
      ],
    },
    {
      id: 'eeg-embroidery',
      minor: true,
      short: 'an embroidered interface that responds to EEG',
      title: 'EEG Embroidery',
      year: '2023',
      blurb: 'Embroidered interface where conductive stitches respond to EEG signal.',
      tags: ['eeg interfaces', 'embroidery', 'soft interaction'],
      figure: 'Embroidered interface; conductive thread paths overlaid with EEG signal traces.',
      body: 'An embroidered soft interface where conductive stitches respond to EEG signal.',
      meta: [
        ['role', 'Sole author'],
        ['context', 'Studio probe'],
        ['tools', 'EEG · conductive thread · embroidery'],
        ['output', 'Soft interface prototype'],
      ],
    },
    {
      id: 'yousan',
      proto: true,
      venue: 'Course project',
      short: 'an interactive umbrella that replays co-walking rain memories',
      title: 'You San',
      subtitle: 'An interactive umbrella that replays co-walking rain memories through thermal trace projection and ambient audio.',
      year: '2026',
      blurb: 'When two people co-hold the handle, the umbrella records ambient rain audio and a low-resolution thermal trace. Later, when one person holds the handle alone with both hands, a projector renders an animated heat map inside the canopy paired with the stored rain sound.',
      tags: ['teleabsence', 'tangible interaction', 'memory objects', 'thermal experience'],
      thumb: 'projects/assets/yousan/ys01-storyboard.png',
      figures: [
        ['assets/yousan/ys01-storyboard.png', 'Two people co-hold the handle and the umbrella records. Later the stored thermal trace is projected onto the interior canopy. Memory is stored as trace, not content.'],
        ['assets/yousan/ys02-system.png', 'The three modes across a walk: ordinary use, co-holding as the capture gate, and the later solo two-hand grasp that replays the most recent trace.'],
        ['assets/yousan/ys03-hardware.png', 'Thermal camera, copper tape electrodes, microphone, pico-projector and speaker in a 3D-printed handle enclosure that replaces the store-bought one.'],
        ['assets/yousan/ys05-handle.png', 'Projector lens, the exploded handle enclosure, and the printed handle in place. The two copper rings are the capacitive electrodes that read how the handle is held.'],
        ['assets/yousan/ys04-dataflow.png', 'Sensor input streams from the umbrella to a nearby PC, which runs the interaction logic, renders the heat map and plays the audio back through the projector and speaker.'],
      ],
      figure: 'Interaction storyboard: co-holding in the rain, and the thermal trace replayed on the canopy later.',
      body: 'Many moments of intimacy emerge through shared sensory experiences, yet they are poorly supported by systems that prioritise explicit messages and visual records over subtle traces. You San treats memory as trace rather than content, and recall as a ritual rather than a library. Co-holding the handle is both a social and a technical gate: it signals that the moment is shared and it is the only configuration in which the system records. Held any other way the umbrella stays idle, so the object still feels like an umbrella rather than a device that is always watching. Only the most recent trace is stored. Drawing on teleabsence, the felt presence of an absent other evoked through material traces, the work adapts the notion from contexts of loss to everyday separation.',
      meta: [
        ['context', 'Course project'],
        ['tools', 'ESP32-S3 Sense · MLX90640 thermal camera · copper tape capacitive electrodes · Kodak Luma 75 pico-projector with fisheye lens · 3D-printed handle'],
        ['output', 'Working prototype'],
      ],
      process: [
        'Three modes governed by how the handle is held: present (two people co-holding, the only state that records), idle (ordinary use, no capture or replay), and absent (one person holding with both hands, which replays the most recent trace).',
        'Two copper tape rings around the handle act as independent capacitive electrodes. A two-hand grasp contacts both, a single hand typically one. The electrodes detect contact only, not grip force or any biometric property.',
        'An MLX90640 thermal camera at 32 × 24 captures warmth inside the canopy. The resolution is deliberately coarse: it conveys where warmth was without rendering identifying detail.',
        'Rain audio is recorded on the ESP32-S3 Sense microphone, only while the co-holding configuration is active.',
        'A pico-projector near the top of the shaft, with a wide-angle fisheye lens, spreads the replay across the interior canopy; warmth rising and gathering overhead reads as heat that stayed rather than a screen.',
        'The ESP32-S3 streams touch, thermal frames and audio to a nearby PC over USB. The PC runs the interaction logic as a finite-state machine with warm-up and cool-down timers to debounce grip changes while walking, and applies temporal smoothing and fades so the projection reads as a shifting warmth shadow.',
      ],
    },
    {
      id: 'memo-umbrella',
      minor: true,
      short: 'an umbrella that remembers where you were when it rained',
      title: 'Memo Umbrella',
      year: '2023',
      blurb: 'An umbrella that records where you were and who you were with when it rained.',
      tags: ['tangible interaction', 'memory objects', 'intimate computing'],
      figure: 'Umbrella with its memory layer inside and the exterior unchanged.',
      body: 'The umbrella keeps a record of where you were and who you were with when it rained. The exercise was to add memory to a familiar object without changing how it looks.',
      meta: [
        ['role', 'Sole author'],
        ['context', 'RISD · ID'],
        ['tools', 'Embedded electronics · prototyping'],
        ['output', 'Working prototype'],
      ],
    },
    {
      id: 'icarus',
      minor: true,
      short: 'a short text game where every choice trades altitude for time',
      title: 'Icarus Text Webgame',
      year: '2023',
      blurb: 'Short text-driven webgame about flight and failure.',
      tags: ['narrative interaction', 'webgame', 'speculative interface'],
      figure: 'Branching dialogue tree of a single playthrough.',
      body: 'A short text-driven webgame where choices trade altitude against time.',
      meta: [
        ['role', 'Sole author'],
        ['context', 'Personal'],
        ['tools', 'JavaScript · narrative design'],
        ['output', 'Playable webgame'],
      ],
    },
    {
      id: 'elp',
      short: 'three protein variants that curl differently in humidity',
      venue: 'HTGAA 2026',
      wip: true,
      title: 'Sequence-Programmed Hygromorphic Coatings',
      year: '2026',
      blurb: 'Three protein variants differ by one amino acid in the repeat unit. The pipeline stays the same and the coatings curl differently in humidity.',
      tags: ['biofabrication', 'responsive materials', 'sequence-encoded behavior'],
      figure: 'Three ELP variants (VPGSG · VPGAG · VPGVG); humidity-driven curling on PET/Mylar bilayers.',
      body: 'Three elastin-like polypeptide variants are designed along a hydrophilicity gradient by changing the guest residue in the repeating VPGXG motif. The biological and fabrication pipeline is held constant, so the sequence is the only variable. Coated on thin PET film, each variant bends and curls differently as humidity changes.',
      meta: [
        ['role', 'Lead researcher'],
        ['context', 'HTGAA 2026 final project'],
        ['tools', 'Benchling · Twist Bioscience · E. coli expression · ELP design · PET/Mylar bilayers · humidity testing'],
        ['output', 'Course final project'],
        ['status', 'Sequence design and workflow done; lab work ongoing'],
      ],
      process: [
        'Design ELP variants with controlled guest-residue substitutions: VPGSG, VPGAG, VPGVG.',
        'Use a consistent biological and fabrication pipeline across all sequence variants.',
        'Fabricate one-sided ELP coatings on thin PET/Mylar films to create responsive bilayer strips.',
        'Evaluate humidity-driven bending, curling, swelling, recovery, coating morphology, cyclic stability.',
        'Treat the sequence as the design variable for responsive biomaterial coatings.',
      ],
    },
    {
      id: 'biochar',
      short: 'biochar tuned until it prints',
      wip: true,
      title: 'Biochar-Based Direct Ink Writing',
      year: '2025–2026',
      blurb: 'Biochar formulations tuned until they extrude and hold their shape in direct ink writing.',
      tags: ['sustainable materials', 'direct ink writing', 'material formulation'],
      figure: 'Biochar DIW test strips; extrusion behavior and print stability across formulation iterations.',
      body: 'Biochar is a carbon-rich waste product. This project adjusts biochar-based formulations until they can be printed by direct ink writing, and evaluates each formulation by how it extrudes, whether the print holds its shape, and how the samples come out.',
      meta: [
        ['role', 'Research assistant · formulation and print-testing contributor'],
        ['context', 'Harvard GSD MaP+S, with Dan Tish & Martin Bechthold; with Jennifer Lewis Lab'],
        ['tools', 'Biochar · direct ink writing · formulation testing · extrusion printing · sample fabrication'],
        ['output', 'Printed samples · research documentation'],
        ['status', 'Formulation and printing done; documentation in progress'],
      ],
      process: [
        'Adjust biochar-based formulations for DIW printability.',
        'Test extrusion behavior, material consistency, and basic print stability.',
        'Produce printed sample strips and test specimens for documentation and evaluation.',
        'Prepare figures and documentation for the current stage.',
      ],
    },
  ],
};

window.PORTFOLIO_DATA = PORTFOLIO_DATA;
